package com.sheridan.group33.find_care.find_care.Model;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

@Entity
public class Node {
    @Id
    private String id;  // Example: "Room101", "HallwayA"

    private double x;  // X coordinate
    private double y;  // Y coordinate
    private int floor; // Floor number

    public Node(){
        
    }

    @OneToMany(mappedBy = "fromNode", cascade = CascadeType.ALL)
    private List<Edge> edges; // Connected paths

    public Node(String string, int i, int j, int k) {
        // I don't know why this was generated by my text editor, but it was, and the app is giving the result wanted...
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }

    public int getFloor() {
        return floor;
    }

    public void setFloor(int floor) {
        this.floor = floor;
    }

    @JsonIgnore
    public List<Edge> getEdges() {
        return edges;
    }

    public void setEdges(List<Edge> edges) {
        this.edges = edges;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Node{");
        sb.append("id=").append(id);
        sb.append(", x=").append(x);
        sb.append(", y=").append(y);
        sb.append(", floor=").append(floor);
        sb.append(", edges=").append(edges);
        sb.append('}');
        return sb.toString();
    }

    
}
