spring.application.name=find_care

server.port=3333

spring.h2.console.enabled = true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

spring.datasource.url=jdbc:h2:mem:find_care
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = ms
spring.datasource.password = ms
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none


# Enable SQL logging
spring.jpa.show-sql=true

# Format SQL queries for better readability
spring.jpa.properties.hibernate.format_sql=true

# Enable logging of SQL queries
logging.level.org.hibernate.SQL=DEBUG

# Enable logging of SQL query parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE